### ISSUE TITLE
Table insert bug

### ISSUE THREAD

**Issue by proweb** [froala/joomla-froala-editor#5]
Wrong dropdown alignment
Can't normal work with tables.
Think this must be problem:
``` css
.editor {
  overflow: hidden;
  position: relative;
}
```

![table_bag](https://cloud.githubusercontent.com/assets/680073/7345136/a138187e-ecda-11e4-829c-5b0bd368a6a6.png)
